<?php
		require('conexion.php');
		require('redireccion.php');
        
?>
<html>

<head>
<meta http-equiv="Content-Language" content="es">
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<meta name="GENERATOR" content="Microsoft FrontPage 6.0">
<meta name="ProgId" content="FrontPage.Editor.Document">
<title>Leonardo Dri</title>
</head>

<body bgcolor="#D8D3B1">

<p><b><font face="Arial" size="5">Leonardo Dri</font><font face="Arial" size="4">,
nacido en Pordenone, Udine, inmigr� en 1892 aproximadamente, casado con Rosa
del Fratte. Se radicaron en Rosario.&nbsp;</font></b></p>






<table border="0" cellpadding="0" cellspacing="0" width="100%">
  <tr>
    <td width="24%" align="center"><font face="Arial" size="4"><b><u>HIJOS </u></b></font></td>
    <td width="27%" align="center"><font face="Arial" size="4"><b><u>NIETOS</u></b></font></td>
    <td width="27%" align="center"><font face="Arial" size="4"><b><u>BISNIETOS</u></b></font></td>
    <td width="15%"></td>
    <td width="7%"></td>
  </tr>
  <tr>
    <td width="24%" align="center">
      <p align="left"><font face="Arial" size="4"><b>Giacomo </b></font><font face="Arial" size="2"><b>(Muzzana
      del Turgano, 13/9/1871)</b></font></td>
    <td width="27%" align="center"></td>
    <td width="27%" align="center"></td>
    <td width="15%"></td>
    <td width="7%"></td>
  </tr>
  <tr>
    <td width="24%">&nbsp;
      <p><font face="Arial"><b><font size="4">Santiago</font> <font size="2">(Pordenone,
      1888 ?- ) Imigr� con su madre en 1902 </font><font size="4">- Mar�a
      Caviglia </font><font size="2">(se radicaron en Cha�ar Ladeado, Santa Fe)</font></b></font></p>
    </td>
    <td width="27%"></td>
    <td width="27%"></td>
    <td width="15%"></td>
    <td width="7%"></td>
  </tr>
  <tr>
    <td width="24%" rowspan="2">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<b><span style="mso-bidi-font-size: 10.0pt"><font face="Arial" size="3"><img border="0" src="IMAGES/Flechitas/l0aresre.gif" width="32" height="32"></font></span></b>
    </td>
    <td width="27%"></td>
    <td width="27%" rowspan="2"></td>
    <td width="15%" rowspan="2"></td>
    <td width="7%" rowspan="2"></td>
  </tr>
  <tr>
    <td width="27%">&nbsp;<p><font face="Arial"><b>Rosa - Arturo A. Fern�ndez</b></font></td>
  </tr>
  <tr>
    <td width="24%" rowspan="2"></td>
    <td width="27%" rowspan="2">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<b><span style="mso-bidi-font-size: 10.0pt"><font face="Arial" size="3"><img border="0" src="IMAGES/Flechitas/l0aresre.gif" width="32" height="32"></font></span></b>&nbsp;</td>
    <td width="27%"></td>
    <td width="15%" rowspan="2"></td>
    <td width="7%" rowspan="2"></td>
  </tr>
  <tr>
    <td width="27%"><b><font face="Arial">Carlos Fern�ndez Dri (radicado en Lavallol)</font></b></td>
  </tr>
  <tr>
    <td width="24%"></td>
    <td width="27%"><font face="Arial"><b>Leonardo</b></font></td>
    <td width="27%"></td>
    <td width="15%"></td>
    <td width="7%"></td>
  </tr>
  <tr>
    <td width="24%"></td>
    <td width="27%"><font face="Arial"><b>Jacinto</b></font></td>
    <td width="27%"></td>
    <td width="15%"></td>
    <td width="7%"></td>
  </tr>
  <tr>
    <td width="24%"></td>
    <td width="27%"><font face="Arial"><b>Delia</b></font></td>
    <td width="27%"></td>
    <td width="15%"></td>
    <td width="7%"></td>
  </tr>
  <tr>
    <td width="24%"></td>
    <td width="27%"><font face="Arial"><b>Osvaldo</b></font></td>
    <td width="27%"></td>
    <td width="15%"></td>
    <td width="7%"></td>
  </tr>
  <tr>
    <td width="24%"></td>
    <td width="27%"><font face="Arial"><b>&quot;Nito&quot;</b></font></td>
    <td width="27%"></td>
    <td width="15%"></td>
    <td width="7%"></td>
  </tr>
  <tr>
    <td width="24%"></td>
    <td width="27%"><font face="Arial"><b>x</b></font></td>
    <td width="27%"></td>
    <td width="15%"></td>
    <td width="7%"></td>
  </tr>
  <tr>
    <td width="24%"></td>
    <td width="27%"><font face="Arial"><b>x</b></font></td>
    <td width="27%"></td>
    <td width="15%"></td>
    <td width="7%"></td>
  </tr>
</table>

<img src="http://visit.geocities.com/visit.gif?1027771477" border=0></noscript>
<IMG SRC="http://geo.yahoo.com/serv?s=76001068&t=1027771477" ALT=1>

</body>

</html>
<!-- text below generated by server. PLEASE REMOVE --></noscript></script><script language="JavaScript" src="http://us.i1.yimg.com/us.yimg.com/i/mc/mc.js"></script><script language="JavaScript" src="http://us.geocities.com/js_source/geov2.js"></script><script language="javascript">geovisit();</script><noscript>
<p><font face="Arial"><o:p>
 <span lang="ES-MX" style="mso-ansi-language:ES-MX"><font size="4" face="Arial">
<a target="_self" href="inmigrantes_a_la_argentina_y_al.htm">
<img border="0" src="IMAGES/Flechitas/7.gif" width="45" height="38">
 Volver
 a Inmigrantes a Argentina y Uruguay</a></font></span></o:p></font></p>
